### PR TITLE
残りのAPI作成

### PR DESCRIPTION
**Pull request by lll-lll-lll-lll**
# TODO
- [x] `communities/comminity_id/users/` api作成
- [x] `/users/:id/articles`　API作成
- [x] ` /users/:id/articles/:article_id`　API作成
- [x]  `articles/` API作成

### CODE REVIEW

**Comment by lll-lll-lll-lll** [comment]
[commit](https://github.com/jphacks/F_2204/pull/21/commits/a523558b4afee71ef7b8aae5b3d4fe30be35942e)
users/user_id/articles api DONE

**Comment by lll-lll-lll-lll** [comment]
`users/user_id/articles/article_id` api DONE

**Comment by kengo78** [comment]
LGTM

**Comment by kengo78** [comment]
mergeしました！

**Pull request merged**
